name: CI PR/Branch
on:
  push:
    branches-ignore:
      - master
  pull_request:

env:
  IMAGE_NAME: "homecentr/mkdocs-material"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up java for tests execution
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Set tag var
        id: vars
        run: echo ::set-output name=docker_tag::$(echo ${GITHUB_REF} | cut -d'/' -f3)-${GITHUB_SHA}

      - name: Verify Dockerfile with Hadolint
        uses: brpaz/hadolint-action@master      

      - name: Build Docker image
        run: docker build . -t ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.docker_tag }}

      - name: Test Docker image
        run: cd tests && sudo gradle test --info -Dimage_tag=${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.docker_tag }}

      - name: Scan with Phonito Security
        uses: phonito/phonito-scanner-action@master
        with:
          image: ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.docker_tag }}
          fail-level: 'HIGH'
          phonito-token: '${{ secrets.PHONITO_TOKEN }}'

      - name: Scan with Snyk
        uses: snyk/actions/docker@0.1.1
        continue-on-error: true # Errors ignored, the image contains high severity issue which does not have a fix yet
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.docker_tag }}
          args: --severity-threshold=high